service_name: travis-pro
repo_token: f5uUaWhxtRI0sFBbsLWAsIwizZYYiUPRu
sudo: required
dist: trusty
language: node_js
node_js:
  - '9.4.0'
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install --save-dev solidity-coverage
  - npm install --save-dev truffle-hdwallet-provider
  - npm install
script:
  - truffle test --network development
before_script:
  - testrpc --network-id 15 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c0,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c1,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c2,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c3,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c4,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c5,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c6,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c7,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c8,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006c9,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006d0,100000000000000000000000000000000000 --account=0x42551cf8b134329c39e611b6cf21aac0f0eeae787f378c69b4ddf76aa1b006d1,100000000000000000000000000000000000 > /dev/null &
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls